---
- name: Install base packages
  package:
    name:
      - htop
      - tree
      - neovim
      - cron-apt
      - autojump
      - ripgrep
      - zsh
      - unzip
      - tar
    state: present

- apt_repository:
    repo: "deb http://deb.debian.org/debian buster-backports main contrib non-free"
    state: present
    update_cache: yes

- name: Install global aliases
  template: src=alias.sh dest=/etc/profile.d/

- hostname:
    name: "{{ server_name }}"

- name: Add hostname to /etc/hosts
  lineinfile:
    path: /etc/hosts
    line: "127.0.0.1 {{ server_name }}"

- name: Set timezone to Europe/Oslo
  timezone:
    name: '{{ timezone }}'

- name: Adding existing user '{{ item }}' to group sudo
  user:
    name: '{{ item }}'
    groups:
      - systemd-journal
    shell: /bin/bash
    append: yes
  with_items: "{{ users }}"

- name: Set authorized keys taken from url
  ansible.posix.authorized_key:
    user: lenni
    state: present
    key: https://github.com/leonardehrenfried.keys

- name: Install systemd files for podman-prune
  template: src={{ item }} dest=/etc/systemd/system/
  with_items:
    - podman-prune.service
    - podman-prune.timer

- name: Start podman-prune.timer
  systemd:
    name: podman-prune.timer
    state: started
    enabled: yes
    daemon_reload: yes

- name: Copy notification script
  template:
    src: "{{ item }}"
    dest: /usr/local/bin
    mode: 711
  with_items:
    - send-to-matrix
    - systemd-failure-notification

- name: Install journald.conf
  template: src={{ item }} dest=/etc/systemd/
  with_items:
    - journald.conf
  notify: Restart systemd-journald

