---
# silence ansible warnings
ansible_python_interpreter: auto_silent
networks_cli_compatible: no

timezone: Europe/Oslo

users:
  - lenni

firewall_allowed_tcp_ports:
  - "22"
  - "80"
  - "443"

# firewall
firewall_state: started
firewall_enabled_at_boot: true
firewall_flush_rules_and_chains: false
# ssh hardening
network_ipv6_enable: true
ssh_allow_agent_forwarding: true
ssh_permit_tunnel: true
ssh_allow_tcp_forwarding: 'yes'
sftp_enabled: true
sftp_chroot: true


# one week
podman_prune_max_age: 604800

matrix_bot_token: 111
