#! /usr/bin/env bash

set -e

PBF_DOWNLOAD_URL={{ pbf_download_url }}
PBF_FILE=norway.osm.pbf

if [ -f "$PBF_FILE" ]; then
  echo "$PBF_FILE exists. Downloading updates."
  pyosmium-up-to-date -v $PBF_FILE
else
  echo "$PBF_FILE does not exist."
  curl --fail --location -s "${PBF_DOWNLOAD_URL}" -o ${PBF_FILE}
fi

osmium tags-filter $PBF_FILE w/buskerudbyen:cycleway -o norway-filtered.pbf -f pbf --overwrite

styles=("existing" "proposed")

for i in "${styles[@]}"
do
   :
  osmium tags-filter norway-filtered.pbf w/buskerudbyen:cycleway=$i -o cycleway-$i.pbf -f pbf --overwrite
  osmium export cycleway-$i.pbf -o cycleway-$i.geojson --overwrite
done

# build tiles with tippecanoe
podman run --rm \
  --entrypoint tippecanoe \
  -v /var/tilemaker:/tilemaker:z \
    docker.io/morlov/tippecanoe \
      --drop-densest-as-needed \
      --output-to-directory=tilemaker/tiles/ \
      --no-tile-compression \
      --log-driver=journald \
      --force \
      tilemaker/cycleway-existing.geojson \
      tilemaker/cycleway-proposed.geojson

send-to-matrix "tilemaker successful"

