#! /usr/bin/env fish

set PBF_DOWNLOAD_URL {{ pbf_download_url }}
set PBF_FILE norway.osm.pbf

if test -f "$PBF_FILE"
  echo "$PBF_FILE exists. Downloading updates."
  pyosmium-up-to-date -v $PBF_FILE
else
  echo "$PBF_FILE does not exist."
  curl --location --fail -s "$PBF_DOWNLOAD_URL" -o $PBF_FILE
end

osmium tags-filter $PBF_FILE w/buskerudbyen:cycleway -o norway-filtered.pbf -f pbf --overwrite

for i in "existing" "proposed"
  osmium tags-filter norway-filtered.pbf w/buskerudbyen:cycleway=$i -o cycleway-$i.pbf -f pbf --overwrite
  osmium export cycleway-$i.pbf -o cycleway-$i.geojson --overwrite
end

# build tiles with tippecanoe
podman run --rm \
  --entrypoint tippecanoe \
  -v /var/tilemaker:/tilemaker:z \
    docker.io/morlov/tippecanoe \
      --drop-densest-as-needed \
      --output-to-directory=tilemaker/tiles/ \
      --no-tile-compression \
      --force \
      tilemaker/cycleway-existing.geojson \
      tilemaker/cycleway-proposed.geojson

mb-util --image_format=pbf norway-filtered.mbtiles tiles

send-to-matrix "tilemaker successful"

