#! /usr/bin/env bash

set -e

PBF_DOWNLOAD_URL={{ pbf_download_url }}
PBF_FILE=norway.osm.pbf

if [ -f "$PBF_FILE" ]; then
  echo "$PBF_FILE exists. Downloading updates."
  pyosmium-up-to-date -v $PBF_FILE
else
  echo "$PBF_FILE does not exist."
  curl --fail --location -s "${PBF_DOWNLOAD_URL}" -o ${PBF_FILE}
fi

echo "Extracting cycleways"
osmium tags-filter $PBF_FILE w/buskerudbyen:cycleway -o norway-filtered.pbf -f pbf --overwrite

styles=("existing" "proposed" "external")

for i in "${styles[@]}"
do
   :
  echo "Extracting OSM features for cycleway=${i}"
  osmium tags-filter norway-filtered.pbf w/buskerudbyen:cycleway=$i -o cycleway-$i.pbf -f pbf --overwrite
  osmium export cycleway-$i.pbf -o cycleway-$i.geojson --overwrite
done

echo "Extracting OSM features for railway stations and places"
osmium extract norway.osm.pbf --polygon buskerudbyen-and-around.geojson -o buskerudbyen-and-around.osm.pbf --overwrite
# extract all railway stations + liebyen and svelvik
osmium tags-filter buskerudbyen-and-around.osm.pbf nw/railway=station n/wikidata=Q12004287 n/wikidata=Q2072812 -o place.osm.pbf -f pbf --overwrite
osmium export place.osm.pbf -o place.geojson --overwrite

# build tiles with tippecanoe
podman run --rm \
  --log-driver=journald \
  --entrypoint tippecanoe \
  -v /var/tilemaker:/tilemaker:z \
    docker.io/morlov/tippecanoe \
      -z20 \
      --no-progress-indicator \
      --output-to-directory=tilemaker/tiles/byvekstavtale/ \
      --no-tile-compression \
      --force \
      tilemaker/cycleway-existing.geojson \
      tilemaker/cycleway-proposed.geojson \
      tilemaker/cycleway-external.geojson \
      tilemaker/place.geojson

# build cycle infrastructure

#send-to-matrix "tilemaker successful"

