#! /usr/bin/env bash

set -e

PBF_DOWNLOAD_URL={{ pbf_download_url }}
PBF_FILE=norway.osm.pbf

OCEAN_SHAPEFILE_URL=https://osmdata.openstreetmap.de/download/water-polygons-split-4326.zip
OCEAN_SHAPEFILE_FOLDER=water-polygons-split-4326
OCEAN_SHAPEFILE_ZIP=${OCEAN_SHAPEFILE_FOLDER}.zip
OCEAN_SHAPEFILE_FINAL_FOLDER=coastline

LANDCOVER_FOLDER=landcover

if [ -f "$PBF_FILE" ]; then
  echo "$PBF_FILE exists. Downloading updates."
  pyosmium-up-to-date -v $PBF_FILE
else
  echo "$PBF_FILE does not exist."
  curl --fail --location -s "${PBF_DOWNLOAD_URL}" -o ${PBF_FILE}
fi

# every Monday we delete the coastline shapefiles and re-download them
if [[ $(date +"%u") -eq 1 ]]; then
  echo "Deleting coastline shapefiles"
  rm -rf ${OCEAN_SHAPEFILE_FINAL_FOLDER}
fi

if [ ! -d "${OCEAN_SHAPEFILE_FINAL_FOLDER}" ]; then
  echo "Downloading coastline shapefiles"
  curl --fail ${OCEAN_SHAPEFILE_URL} -o ${OCEAN_SHAPEFILE_ZIP}
  unzip ${OCEAN_SHAPEFILE_ZIP}
  mv ${OCEAN_SHAPEFILE_FOLDER} ${OCEAN_SHAPEFILE_FINAL_FOLDER}
  rm ${OCEAN_SHAPEFILE_ZIP}
fi

if [ ! -d "${LANDCOVER_FOLDER}" ]; then
  mkdir -p landcover/ne_10m_urban_areas
  cd landcover/ne_10m_urban_areas
  wget https://www.naturalearthdata.com/http//www.naturalearthdata.com/download/10m/cultural/ne_10m_urban_areas.zip
  unzip -o ne_10m_urban_areas.zip
  rm -rf ne_10m_urban_areas.zip

  cd ..
  mkdir -p ne_10m_antarctic_ice_shelves_polys

  cd ne_10m_antarctic_ice_shelves_polys
  wget https://www.naturalearthdata.com/http//www.naturalearthdata.com/download/10m/physical/ne_10m_antarctic_ice_shelves_polys.zip
  unzip -o ne_10m_antarctic_ice_shelves_polys.zip
  rm -rf ne_10m_antarctic_ice_shelves_polys.zip

  cd ..
  mkdir -p ne_10m_glaciated_areas

  cd ne_10m_glaciated_areas
  wget https://www.naturalearthdata.com/http//www.naturalearthdata.com/download/10m/physical/ne_10m_glaciated_areas.zip
  unzip -o ne_10m_glaciated_areas.zip
  rm -rf ne_10m_glaciated_areas.zip
fi

podman stop tilemaker-map || true
podman rm tilemaker-map || true

echo "Buildings tiles with tilemaker"
podman run \
  -it \
  -v /var/tilemaker/coastline:/coastline:z \
  -v /var/tilemaker/landcover:/landcover:z \
  -v /var/tilemaker/:/srv:z \
  --name tilemaker-map \
  --rm \
  --cpu-shares 512 \
  docker.io/stadtnavi/tilemaker:a3c70afb7685cb642da8424eba9863ca37bbc32c \
  /srv/${PBF_FILE} \
  --output=/srv/tiles/bicycle/{{ bicycle_tiles_version }}/  \
  --config=/srv/bicycle/config-openmaptiles.json \
  --process=/srv/bicycle/process-openmaptiles.lua \
  --store=/root/store \

send-to-matrix "🇳🇴 tilemaker-map successful"

