---
- name: Install packages
  apt:
    state: latest
    default_release: bullseye-backports
    name:
      - pyosmium
      - osmium-tool
      - curl
      - build-essential
      - python3-dev
      - python3-flask
      - pip

- name: Create data directory
  file:
    path: "{{ tilemaker_dir }}"
    state: directory
    owner: root
    group: root
    mode: 0775

- name: Install config and script files
  template:
    src: "{{ item }}"
    dest: /var/tilemaker/
    mode: a+x
  with_items:
    - build-tiles
    - build-map
  notify: Restart tilemaker

- name: Install config
  template:
    src: "{{ item }}"
    dest: /var/tilemaker/
  with_items:
    - buskerudbyen-and-around.geojson
    - process-openmaptiles.lua
    - config-openmaptiles.json
  notify: Restart tilemaker

- name: Install bicycle style config
  template:
    src: "{{ item }}"
    dest: /var/tilemaker/bicycle/
  with_items:
    - bicycle/process-openmaptiles.lua
    - bicycle/config-openmaptiles.json

- name: Install length calculation
  template:
    src: "{{ item }}"
    dest: /var/tilemaker/
  with_items:
    - cycleway_length.py
    - cycleway_length.wsgi
  notify: Restart apache

- name: Install systemd files
  template: src=systemd/{{ item }} dest=/etc/systemd/system/
  with_items:
    - tilemaker.service
    - tilemaker.timer
    - tilemaker-map.service
  notify: Restart tilemaker

- name: Start tilemaker.timer
  systemd:
    name: tilemaker.timer
    state: started
    enabled: yes
    daemon_reload: yes

