---
- name: Install packages
  apt:
    state: latest
    default_release: bullseye-backports
    name:
      - pyosmium
      - osmium-tool
      - curl
      - build-essential
      - python3-dev
      - pip

- name: Create data directory
  file:
    path: "{{ tilemaker_dir }}"
    state: directory
    owner: root
    group: root
    mode: 0775

- name: Install config and script files
  template:
    src: "{{ item }}"
    dest: /var/tilemaker/
    mode: a+x
  with_items:
    - build-mbtiles
    - compute-cycleway-length

  notify: Restart tilemaker

- name: Install systemd files
  template: src={{ item }} dest=/etc/systemd/system/
  with_items:
    - tilemaker.service
    - tilemaker.timer
  notify: Restart tilemaker

- name: Start tilemaker.timer
  systemd:
    name: tilemaker.timer
    state: started
    enabled: yes
    daemon_reload: yes

