---
- name: Install systemd files
  template: src=systemd/{{ item }} dest=/etc/systemd/system/
  with_items:
    - otp.service

- name: Start services
  systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
    daemon_reload: yes
  with_items:
    - otp.service


